FROM node:12.13.1 as builder

RUN mkdir /app/ && \
    mkdir /publish/

WORKDIR /app/

RUN npm install -g @angular/cli
ADD ./package.json ./
RUN npm install
ADD ./ ./
RUN ls
RUN ng build --output-path /publish/

FROM nginx
COPY --from=builder /publish/ /usr/share/nginx/html



